name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew update
          brew install ffmpeg
      - name: Run test_shortcuts.sh
        run: bash tests/test_shortcuts.sh
      - name: Run test_audio_only_for_low_motion.sh
        run: bash tests/test_audio_only_for_low_motion.sh
